---
# tasks file for k8s-master
# - name: install docker
#   package:
#     name: "{{ item }}"
#     state: present
#   loop: 
#     - docker
#     #- iproute-tc

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Disable swap since kubernetes can't work with swap enabled
  command: swapoff -a

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- name: Add Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes Repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Installing Kubernetes Cluster Packages.
  apt: 
    name:
      - kubeadm
      - kubectl
      - kubelet
    state: present

- name: Enabling docker and kubelet services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker

- name: copy daemon.json file for changing cgroup driver to systemd
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker service

- meta: flush_handlers

- name: Enable service kubelet, and enable persistently
  service: 
    name: kubelet
    enabled: yes

# - name: pull config images
#   command: sudo kubeadm config images pull

- name: copying k8s conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: refreshing sysctl
  shell: "sysctl --system"  

- name: initializing  kubeadm service
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: yes   

- name: Creating the directory
  file:
    name: "$HOME/.kube"
    state: directory

- name: Copy conf file
  command: "cp  /etc/kubernetes/admin.conf $HOME/.kube/config"
  ignore_errors: yes

- name: Doing some required thing
  shell: "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Installing flannel
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: Generate join command
  shell: "kubeadm token create --print-join-command"
  register: kubeadm_join_command

- name: debugging
  debug:
    var: kubeadm_join_command.stdout
